name: CI

env:
  GITHUB_FEED: https://nuget.pkg.github.com/EmptyBucket/index.json
  GITHUB_USER: EmptyBucket

  NUGET_FEED: https://api.nuget.org/v3/index.json

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1

    - name: Create Release NuGet package
      run: dotnet pack -c Release -o packages src
      
    - name: Push to GitHub Feed
      run: |
        for f in ./packages/*.nupkg
        do
          dotnet nuget push $f -s $GITHUB_FEED -k $FLUENTSPECIFICATION_GITHUB_PAT --skip-duplicate
        done
